### ISSUE TITLE
No sound controls visible

### ISSUE THREAD

**Issue by saurabhlambe** [rafaeldelboni/dotfiles#2]
Hello,

I just cloned the repo and switched to this i3 theme. But I'm unable to see the volume control icon. I've installed the fontawesome font too. Please let me know if you need to see some log files. I'm running Arch Linux btw.

![no sound controls](https://user-images.githubusercontent.com/19834688/41819139-f1029c9e-77d8-11e8-94be-34d55477e525.png)

**Comment by rafaeldelboni** [comment]
Hey hello how you doing? 

This is happening because I don't use fontawesome, but nerdfonts which also have all the font awesome built-in and some extra good stuff. Check all about it here:
http://nerdfonts.com/
For arch I use this aur package: nerd-fonts-source-code-pro

**Comment by saurabhlambe** [comment]
Hi Rafael! I'm doing good, thanks!

That did the trick. Installed nerd-fonts-source-code-pro and I was instantly able to see the Volume icon. However, the battery icon is still missing. Any clues to what I might be doing wrong? Thanks in advance.

**Comment by rafaeldelboni** [comment]
Glad to hear!

Could you please, navigate go to the following folder "~/.conf/i3blocks/scripts" and try to execute the battery script? "./battery".
Check if there is any error coming out of this script.

**Comment by saurabhlambe** [comment]
That did the trick! I found that the package 'acpi' wasn't installed. Installed it and the battery icon started working right away!

Thanks for the prompt help @rafaeldelboni ! :)

**Comment by rafaeldelboni** [comment]
Awesome! Have a great day.
